### ISSUE TITLE
Assetstore import fails

### ISSUE THREAD

**Issue by dorukozturk** [shreddd/girder-ess-dive#1]
@shreddd When I try to import from "ess-dive-2f8202e4c0f5ffa-20190215T222733727", the bounding box calculation fails. I see something like:

```sh
  "message": "TypeError: TypeError('list indices must be integers, not str',)",
```

This is happening because 
```py
bbox = metadata['eml:eml']['dataset']['coverage']['geographicCoverage']
```
returns a list. I believe bounding box computation should live inside the for loop while you are looping through the file objects here (https://github.com/shreddd/girder-ess-dive/blob/master/server/assetstore.py#L115). Am I missing something?

**Comment by shreddd** [comment]
Hi Doruk

Can you include the stack trace with this? Where the bbox is computed shouldn't  matter because it is the same across the dataset. My guess is there is a type issue with some data.

-Shreyas

**Comment by dorukozturk** [comment]
The whole stacktrace is here: 
https://gist.github.com/dorukozturk/6c9195c9ec0400a4e0047fb0b307c98f.
I was looking at the essdiveids from the unittests. Is there a specific essdiveid that we should 
work with for the sake of the demo?

**Comment by shreddd** [comment]
OK - I see the issue. This particular dataset has multiple bounding boxes. I'll need to account for that, 
but for now it might be better to use a simpler dataset.

Try: https://data.ess-dive.lbl.gov/view/ess-dive-61001536a05b57d-20190305T125043787962
 
I'll send you an updated link to data this afternoon with the unzipped version as well. 
-Shreyas

**Comment by dorukozturk** [comment]
That sounds fantastic. Thank you !

**Comment by shreddd** [comment]
OK - please grab the latest commits and pull data from (on the ESS-DIVE dev site) here:
https://data-dev.ess-dive.lbl.gov/view/ess-dive-69f396513c526d5-20190312T230557449
